/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import db.OrderController;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import restaurant.MyOrderDB;
import restaurant.ShowDB;


/**
 *
 * @author STUDY fuckin HARD
 */
public class PanelDB extends javax.swing.JPanel {
    private MainGUI mg;
    private ShowDB show;
    private OrderController ordc;
    
    //table
    private Object[] row_table, column_table;
    private DefaultTableModel model;
    
    
    /**
     * Creates new form PanelDB
     */
    public PanelDB() {
        initComponents();
        ordc = new OrderController();;
        show = new ShowDB(ordc.getDataDB());
        myGraph();
        myTabel();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDB = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;   //Disallow the editing of any cell
            }
        };
        jGraphPane = new javax.swing.JTabbedPane();

        setPreferredSize(new java.awt.Dimension(1143, 616));

        jScrollPane1.setBorder(null);

        jTableDB.setBackground(new java.awt.Color(255, 255, 204));
        jTableDB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableDB.setToolTipText("double click to see more detail");
        jScrollPane1.setViewportView(jTableDB);
        jTableDB.getTableHeader().setReorderingAllowed(false);

        jGraphPane.setPreferredSize(new java.awt.Dimension(698, 616));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jGraphPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jGraphPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jGraphPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDB;
    // End of variables declaration//GEN-END:variables

    public void myGraph(){//graph panel and set layout
        //get graph
        jGraphPane.addTab("Price per Day", show.getPricePerDayGraph(show.getPricePerDay()));
        jGraphPane.addTab("Top Menu", show.getTopMenuGraph(show.getTopMenu()));
        
    }
    public void myTabel(){
        column_table = new Object[4];
        row_table = new Object[4];
        column_table[0] = "Order ID";
        column_table[1] = "Price include vat";
        column_table[2] = "Order Date";
        column_table[3] = "User";

        model = new DefaultTableModel();
        model.setColumnIdentifiers(column_table);
        jTableDB.setModel(model);
        ArrayList<MyOrderDB> myoDB = ordc.getDataDB();
        for(int i=0; i<myoDB.size(); i++){
            row_table[0] = myoDB.get(i).getOrderID();
            row_table[1] = myoDB.get(i).getPrice_include_vat();
            row_table[2] = myoDB.get(i).getDate();
            row_table[3] = myoDB.get(i).getUser();
            model.addRow(row_table);
         }
        
        jTableDB.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent evt) {
                JTable table =(JTable) evt.getSource();
                int row = table.rowAtPoint(evt.getPoint()); //evt.getpoint() -> point -> (x,y)
                if (evt.getClickCount() == 2 && table.getSelectedRow() != -1) { //double click on row
                    SelectedOrder select = new SelectedOrder((int) model.getValueAt(row, 0));//send orderID
                    select.setVisible(true);
                    select.setLocationRelativeTo(null);
                }
            }
        });
    }
}
