/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import db.OrderController;
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import print.Receipt;
import restaurant.Order;
import restaurant.MyOrder;

/**
 *
 * @author STUDY fuckin HARD
 */
public class PosGUI extends javax.swing.JPanel {

    private GridBagLayout layout = new GridBagLayout();
    private PanelMainFood pmf;
    private PanelSnack ps;
    private PanelDrink pd;
    private MainGUI mg;
    //table
    private Object[] row_table, column_table;
    DefaultTableModel model;
    private int selected_row;

    MyOrder myo;
    OrderController oc;

    /**
     * Creates new form posGUI
     */
    public PosGUI(MainGUI mg) {
        this.mg = mg;
        initComponents();
        myo = new MyOrder();
        oc = new OrderController();
        pmf = new PanelMainFood(this);
        ps = new PanelSnack(this);
        pd = new PanelDrink(this);
        //dynamic panel and layout
        DynamicPanel.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;
        DynamicPanel.add(pmf, c);
        DynamicPanel.add(ps, c);
        DynamicPanel.add(pd, c);
        //set default
        setColor(jMainFood);
        resetColor(jDrink, jSnack);
        pmf.setVisible(true);
        ps.setVisible(false);
        pd.setVisible(false);

        //table
        column_table = new Object[5];
        column_table[0] = "Qty";
        column_table[1] = "Product";
        column_table[2] = "ราคาต่อจำนวน";
        column_table[3] = "ราคารวม";
        column_table[4] = "หมายเหตุ";
        model = new DefaultTableModel();
        model.setColumnIdentifiers(column_table);
        pos_jTable.setModel(model);
        makeTableAction();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        pos_Panel = new javax.swing.JPanel();
        LeftPanel = new javax.swing.JPanel();
        jDelete = new javax.swing.JButton();
        jSubmit = new javax.swing.JButton();
        jTotal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jDecreseQty = new javax.swing.JButton();
        jIncreseQty = new javax.swing.JButton();
        jReceive = new javax.swing.JTextField();
        jChange = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPrice_vat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pos_jTable = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;   //Disallow the editing of any cell
            }

        };
        jTableInput = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        SelectivePanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jMainFood = new javax.swing.JButton();
        jSnack = new javax.swing.JButton();
        jDrink = new javax.swing.JButton();
        DynamicPanel = new javax.swing.JPanel();

        jLabel5.setText("jLabel5");

        setPreferredSize(new java.awt.Dimension(1143, 616));

        pos_Panel.setBackground(new java.awt.Color(255, 153, 153));

        LeftPanel.setBackground(new java.awt.Color(255, 204, 153));
        LeftPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jDelete.setText("Delete");
        jDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteActionPerformed(evt);
            }
        });

        jSubmit.setText("Submit");
        jSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSubmitActionPerformed(evt);
            }
        });

        jTotal.setEditable(false);
        jTotal.setText("0.0");

        jLabel1.setText("Price");

        jDecreseQty.setText("-");
        jDecreseQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDecreseQtyActionPerformed(evt);
            }
        });

        jIncreseQty.setText("+");
        jIncreseQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIncreseQtyActionPerformed(evt);
            }
        });

        jReceive.setPreferredSize(new java.awt.Dimension(6, 22));

        jChange.setEditable(false);
        jChange.setText("0.0");

        jLabel2.setText("Receive");

        jLabel3.setText("Change");

        jPrice_vat.setEditable(false);
        jPrice_vat.setText("0.0");

        jLabel4.setText("+ Vat 7%");

        pos_jTable.setBackground(new java.awt.Color(255, 255, 204));
        pos_jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Qty", "Product", "ราคาต่อจำนวน", "รวม", "หมายเหตุ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(pos_jTable);
        if (pos_jTable.getColumnModel().getColumnCount() > 0) {
            pos_jTable.getColumnModel().getColumn(0).setResizable(false);
            pos_jTable.getColumnModel().getColumn(1).setResizable(false);
            pos_jTable.getColumnModel().getColumn(2).setResizable(false);
            pos_jTable.getColumnModel().getColumn(3).setResizable(false);
            pos_jTable.getColumnModel().getColumn(4).setResizable(false);
        }
        pos_jTable.getTableHeader().setReorderingAllowed(false);

        jLabel7.setText("Table");

        javax.swing.GroupLayout LeftPanelLayout = new javax.swing.GroupLayout(LeftPanel);
        LeftPanel.setLayout(LeftPanelLayout);
        LeftPanelLayout.setHorizontalGroup(
            LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(LeftPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LeftPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jReceive, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPrice_vat, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChange, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTableInput, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104))
            .addGroup(LeftPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeftPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeftPanelLayout.createSequentialGroup()
                        .addComponent(jDecreseQty)
                        .addGap(9, 9, 9)
                        .addComponent(jIncreseQty)
                        .addGap(19, 19, 19)
                        .addComponent(jDelete))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LeftPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(112, 112, 112)
                        .addComponent(jSubmit)))
                .addContainerGap())
        );
        LeftPanelLayout.setVerticalGroup(
            LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDecreseQty)
                    .addComponent(jIncreseQty)
                    .addComponent(jDelete))
                .addGap(18, 18, 18)
                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jPrice_vat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jReceive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSubmit)
                    .addComponent(jTableInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap())
        );

        jReceive.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                try{
                    double receive = Double.parseDouble(jReceive.getText());
                    myo.setReceive(receive);
                    double change = myo.getReceive() - myo.getPrice_include_vat();
                    myo.setChange(change);
                    String result = String.format("%.2f", myo.getChange());
                    jChange.setText(result);
                }catch(NumberFormatException ex){
                    JOptionPane.showMessageDialog(null, "Use Number");
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                try{
                    double receive = Double.parseDouble(jReceive.getText());
                    double change = receive - myo.getPrice_include_vat();
                    String result = String.format("%.2f",change);
                    jChange.setText(result);
                }catch(NumberFormatException ex){
                    JOptionPane.showMessageDialog(null, "Use Number");
                }
            }
        });

        SelectivePanel.setBackground(new java.awt.Color(255, 153, 204));
        SelectivePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setText("ประเภทอาหาร");

        jMainFood.setBackground(new java.awt.Color(102, 204, 255));
        jMainFood.setText("เมนูหลัก");
        jMainFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMainFoodActionPerformed(evt);
            }
        });

        jSnack.setBackground(new java.awt.Color(204, 204, 255));
        jSnack.setText("เมนูทานเล่น");
        jSnack.setMaximumSize(new java.awt.Dimension(77, 25));
        jSnack.setMinimumSize(new java.awt.Dimension(77, 25));
        jSnack.setPreferredSize(new java.awt.Dimension(77, 25));
        jSnack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSnackActionPerformed(evt);
            }
        });

        jDrink.setBackground(new java.awt.Color(204, 204, 255));
        jDrink.setText("เครื่องดื่ม");
        jDrink.setMaximumSize(new java.awt.Dimension(77, 25));
        jDrink.setMinimumSize(new java.awt.Dimension(77, 25));
        jDrink.setPreferredSize(new java.awt.Dimension(77, 25));
        jDrink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDrinkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SelectivePanelLayout = new javax.swing.GroupLayout(SelectivePanel);
        SelectivePanel.setLayout(SelectivePanelLayout);
        SelectivePanelLayout.setHorizontalGroup(
            SelectivePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectivePanelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel6)
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SelectivePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SelectivePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDrink, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSnack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jMainFood, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        SelectivePanelLayout.setVerticalGroup(
            SelectivePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectivePanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jMainFood, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSnack, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jDrink, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        DynamicPanel.setBackground(new java.awt.Color(255, 102, 102));
        DynamicPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout DynamicPanelLayout = new javax.swing.GroupLayout(DynamicPanel);
        DynamicPanel.setLayout(DynamicPanelLayout);
        DynamicPanelLayout.setHorizontalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 337, Short.MAX_VALUE)
        );
        DynamicPanelLayout.setVerticalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 614, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pos_PanelLayout = new javax.swing.GroupLayout(pos_Panel);
        pos_Panel.setLayout(pos_PanelLayout);
        pos_PanelLayout.setHorizontalGroup(
            pos_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pos_PanelLayout.createSequentialGroup()
                .addComponent(LeftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(SelectivePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(DynamicPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pos_PanelLayout.setVerticalGroup(
            pos_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LeftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(DynamicPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pos_PanelLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(SelectivePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pos_Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pos_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jMainFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMainFoodActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == jMainFood) {
            setColor(jMainFood);
            resetColor(jDrink, jSnack);
            pmf.setVisible(true);
            ps.setVisible(false);
            pd.setVisible(false);
        }
    }//GEN-LAST:event_jMainFoodActionPerformed

    private void jSnackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSnackActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == jSnack) {
            setColor(jSnack);
            resetColor(jDrink, jMainFood);
            pmf.setVisible(false);
            ps.setVisible(true);
            pd.setVisible(false);
        }
    }//GEN-LAST:event_jSnackActionPerformed

    private void jDrinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDrinkActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == jDrink) {
            setColor(jDrink);
            resetColor(jMainFood, jSnack);
            pmf.setVisible(false);
            ps.setVisible(false);
            pd.setVisible(true);
        }
    }//GEN-LAST:event_jDrinkActionPerformed

    private void jIncreseQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIncreseQtyActionPerformed
        // TODO add your handling code here:
        selected_row = pos_jTable.getSelectedRow();
        int value = (int) model.getValueAt(selected_row, 0);
        model.setValueAt(value + 1, selected_row, 0);
        double price_each = (double) model.getValueAt(selected_row, 2);
        model.setValueAt(price_each * (value + 1), selected_row, 3);
        calculatePrice();
    }//GEN-LAST:event_jIncreseQtyActionPerformed

    private void jDecreseQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDecreseQtyActionPerformed
        // TODO add your handling code here:
        selected_row = pos_jTable.getSelectedRow();
        int value = (int) model.getValueAt(selected_row, 0);
        double price_each = (double) model.getValueAt(selected_row, 2);

        if (value > 1) {
            model.setValueAt(value - 1, selected_row, 0);
            model.setValueAt(price_each * (value - 1), selected_row, 3);
        } else {
            model.removeRow(selected_row);
        }
        calculatePrice();
    }//GEN-LAST:event_jDecreseQtyActionPerformed

    private void jSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSubmitActionPerformed
        int res = 0;
        if (!jTableInput.getText().isEmpty()) {
            if (!jReceive.getText().isEmpty()) {
                if (Double.parseDouble(jReceive.getText()) >= Double.parseDouble(jPrice_vat.getText())) {
                    for (int i = 0; i < model.getRowCount(); i++) {
                        int quantity = (int) model.getValueAt(i, 0);
                        String name = (String) model.getValueAt(i, 1);
                        Double price_each = (Double) model.getValueAt(i, 2);
                        Double price = (Double) model.getValueAt(i, 3);
                        String detail = (String) model.getValueAt(i, 4);
                        myo.addFood(new Order(quantity, name, price_each, price, detail));
                    }
                    myo.setUser(mg.getU().getUname());
                    myo.setDate(new Date());
                    myo.setTableNumber(Integer.parseInt(jTableInput.getText()));
                    res = oc.insertOrder(myo);
                } else {
                    JOptionPane.showMessageDialog(null, "Plese fill recieve again", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Plese fill recieve", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Plese fill the table", "ERROR", JOptionPane.ERROR_MESSAGE);
        }

        if (res > 0) {
            Receipt receipt = new Receipt(myo);
            try {
                receipt.saveReceipt();
            } catch (IOException ex) {
                Logger.getLogger(PosGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            System.out.println(receipt.getMyReceipt());
            JOptionPane.showMessageDialog(null, "Finish -> Please Print receipt");
            mg.dispose();
            MainGUI run = new MainGUI(mg.getU());
            run.setVisible(true);
            run.setLocationRelativeTo(null);
        } else {
            JOptionPane.showMessageDialog(null, "Unable to finish ordering");
        }

    }//GEN-LAST:event_jSubmitActionPerformed

    private void jDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteActionPerformed
        // TODO add your handling code here:
        selected_row = pos_jTable.getSelectedRow();
        if (selected_row >= 0) {
            model.removeRow(selected_row);
        } else {
            System.out.println("Cant delete");
        }
        calculatePrice();
    }//GEN-LAST:event_jDeleteActionPerformed

    public void calculatePrice() {
        int temp = 0;
        for (int i = 0; i < model.getRowCount(); i++) {
            temp += (double) model.getValueAt(i, 3);
        }

        myo.setPriceTotal(temp);
        myo.setPrice_include_vat(myo.getPriceTotal());

        DecimalFormat df = new DecimalFormat(".##");
        jTotal.setText(df.format(myo.getPriceTotal()));
        jPrice_vat.setText(df.format(myo.getPrice_include_vat()));
    }

    public boolean checkMenu(String foodname) {
        for (int i = 0; i < model.getRowCount(); i++) {
            if (model.getValueAt(i, 1).equals(foodname)) {
                return true;
            }
        }
        return false;
    }

    public int checkRowDuplicate(String foodname) {
        for (int i = 0; i < model.getRowCount(); i++) {
            if (model.getValueAt(i, 1).equals(foodname)) {
                return i;
            }
        }
        return 0;
    }

    public void setColor(JButton bt) {
        bt.setBackground(new Color(102, 204, 255));
    }

    public void resetColor(JButton bt1, JButton bt2) {
        bt1.setBackground(new Color(204, 204, 255));
        bt2.setBackground(new Color(204, 204, 255));
    }

    public void makeTableAction() {
        pos_jTable.addMouseListener(new MouseAdapter() {
            public void mousePressed(MouseEvent evt) {
                JTable table = (JTable) evt.getSource();
                int row = table.rowAtPoint(evt.getPoint()); //evt.getpoint() -> point -> (x,y)
                if (evt.getClickCount() == 2 && table.getSelectedRow() != -1) { //double click on row
                    JTextField comment = new JTextField();
                    Object[] message = {
                        "หมายเหตุ", comment
                    };
                    int check = JOptionPane.showConfirmDialog(null, message, "หมายเหตุ", JOptionPane.OK_CANCEL_OPTION);
                    if (check == JOptionPane.OK_OPTION) {
                        model.setValueAt(comment.getText(), row, 4);
                    }
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DynamicPanel;
    private javax.swing.JPanel LeftPanel;
    private javax.swing.JPanel SelectivePanel;
    private javax.swing.JTextField jChange;
    private javax.swing.JButton jDecreseQty;
    private javax.swing.JButton jDelete;
    private javax.swing.JButton jDrink;
    private javax.swing.JButton jIncreseQty;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jMainFood;
    private javax.swing.JTextField jPrice_vat;
    private javax.swing.JTextField jReceive;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jSnack;
    private javax.swing.JButton jSubmit;
    private javax.swing.JTextField jTableInput;
    private javax.swing.JTextField jTotal;
    private javax.swing.JPanel pos_Panel;
    private javax.swing.JTable pos_jTable;
    // End of variables declaration//GEN-END:variables
}
